# Generated by Django 2.2 on 2019-04-24 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("todoapp", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="is_deleted",
            field=models.BooleanField(default=False),
        )
    ]
